
#-------------------------------------------------
#
# QtCreator project include file
#
#-------------------------------------------------

INCLUDEPATH += $$LIBTHING_SRC




SOURCES +=     $$LIBTHING_SRC/BoundingBox.cc \
    $$LIBTHING_SRC/LineSegment2.cc \
    $$LIBTHING_SRC/Mesh.cc \
    $$LIBTHING_SRC/Scalar.cc \
    $$LIBTHING_SRC/StlReader.cc \
    $$LIBTHING_SRC/StlWriter.cc \
    $$LIBTHING_SRC/Triangle3.cc \
    $$LIBTHING_SRC/Vector2.cc \
    $$LIBTHING_SRC/Vector3.cc \

HEADERS +=   $$LIBTHING_SRC/BoundingBox.h \
    $$LIBTHING_SRC/Exception.h \
    $$LIBTHING_SRC/LayerMeasure.h \
    $$LIBTHING_SRC/LineSegment2.h \
    $$LIBTHING_SRC/Mesh.h \
    $$LIBTHING_SRC/PlatformTools.h \
    $$LIBTHING_SRC/ProgressBar.h \
    $$LIBTHING_SRC/Scalar.h \
    $$LIBTHING_SRC/StlReader.h \
    $$LIBTHING_SRC/StlWriter.h \
    $$LIBTHING_SRC/Triangle3.h \
    $$LIBTHING_SRC/Vector2.h \
    $$LIBTHING_SRC/Vector3.h \


